apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name | required }}
  labels:
    namespace.sykesdev.ca/purpose: {{ .Values.purpose | required}}
    kubernetes.io/managed-by: Helm
    {{ toYaml .Values.labels }}
