apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    namespace.sykesdev.ca/purpose: {{ .Values.purpose }}
    {{- with .Values.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end -}}
