apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    namespace.sykesdev.ca/purpose: {{ .Values.purpose }}
    kubernetes.io/managed-by: Helm
    {{ toYaml .Values.labels }}
