apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-instance-argocd-application-controller
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-instance-argocd-application-controller
  annotations:
    platform.sykesdev.ca/part-of: argocd-instance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-instance-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: argocd-instance-argocd-application-controller
  namespace: argocd-system