{{- range .Values.addressPools -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ include "metallb.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses: {{ toYaml . | nindent 4 }}
{{- end -}}
