{{- if not (eq (len .Values.addressPools) 0) -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses: {{ toYaml .Values.addressPools | nindent 4 }}
{{- end -}}
