{{- range .Values.addressPools -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  addresses: {{ toYaml .addresses | nindent 4 }}
{{- end -}}
