# Default values for core.

localPathProvisioner:
    namespace:
      name: "local-path-provisioner-system"
      purpose: "system"

    storageClass:
      name: local-path
      defaultClass: true
      reclaimPolicy: Delete

metallb:
  namespace:
    name: "metallb-system"
    purpose: system
    labels:
      pod-security.kubernetes.io/enforce: "privileged"
      pod-security.kubernetes.io/audit: "privileged"
      pod-security.kubernetes.io/warn: "privileged"

  config:
    addressPools: []
      # - name: example
      #   addresses:
      #   - 192.168.0.0/30
