name: Release Charts

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "chart-releaser"
          git config user.email "chart-releaser@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: stable
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
