core:
  enabled: true

  metallb:
    namespace:
      name: "metallb-system"
      purpose: "system"
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged

    config:
      addressPools:
        - 172.20.0.0/30

management:
  clusters:
  - name: in-cluster
    server: https://kubernetes.default.svc
    clusterResources: "true"
    config: '{"tlsClientConfig":{"insecure":false}}'

application:
  enabled: false
